// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVVov0hICrrqu65tBrRgMiGX--gFzxn_U',
    appId: '1:163686784164:web:a4d0eb3a1db51fc38f5a31',
    messagingSenderId: '163686784164',
    projectId: 'spotify-clone-6f6ab',
    authDomain: 'spotify-clone-6f6ab.firebaseapp.com',
    storageBucket: 'spotify-clone-6f6ab.appspot.com',
    measurementId: 'G-L4NPF5099F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMFT6qIoILLEly1DZAuA-RXeOWihGJGIQ',
    appId: '1:163686784164:android:a8b5e769f2cb047e8f5a31',
    messagingSenderId: '163686784164',
    projectId: 'spotify-clone-6f6ab',
    storageBucket: 'spotify-clone-6f6ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgerYv53PsqjqZxsMenfBNI-UpoT_CJfk',
    appId: '1:163686784164:ios:bf2083fa7ebe46378f5a31',
    messagingSenderId: '163686784164',
    projectId: 'spotify-clone-6f6ab',
    storageBucket: 'spotify-clone-6f6ab.appspot.com',
    iosBundleId: 'com.example.avis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgerYv53PsqjqZxsMenfBNI-UpoT_CJfk',
    appId: '1:163686784164:ios:bf2083fa7ebe46378f5a31',
    messagingSenderId: '163686784164',
    projectId: 'spotify-clone-6f6ab',
    storageBucket: 'spotify-clone-6f6ab.appspot.com',
    iosBundleId: 'com.example.avis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVVov0hICrrqu65tBrRgMiGX--gFzxn_U',
    appId: '1:163686784164:web:3515ddcceeab1bb38f5a31',
    messagingSenderId: '163686784164',
    projectId: 'spotify-clone-6f6ab',
    authDomain: 'spotify-clone-6f6ab.firebaseapp.com',
    storageBucket: 'spotify-clone-6f6ab.appspot.com',
    measurementId: 'G-2FPRKFLMN8',
  );
}
